### ISSUE TITLE
icon for root- checker

### ISSUE THREAD

**Issue by somratking420** [BharathVishal/Root-Checker#1]
hi @BharathVishal, I am a graphic designer, I want to help you in graphic design.

After I review your project, your app is very good. Therefore I suggest a new logo and icon for you. If you want it, I will design it for you and it's free.

**Comment by BharathVishal** [comment]
Sounds good. Thanks for your proposal. Feel free to design a logo under Apache 2.0 license. I'll add your name in Readme.md for logo designing.

**Comment by somratking420** [comment]
hi @bharathvishal,this is logo for your  project. pleased  tell me logo size.
![root](https://user-images.githubusercontent.com/40878798/42799790-f8c20980-89ba-11e8-88af-f6c3e5524891.png)

**Comment by BharathVishal** [comment]
The logo is good. 100 x 100 pixels would be fine.

**Comment by somratking420** [comment]
@BharathVishal  sir

**Comment by BharathVishal** [comment]
Hi, 
You can give a pull request and add the icon. Thanks.

**Comment by somratking420** [comment]
hi @BharathVishal sir full requests #2

**Comment by BharathVishal** [comment]
Hi, I have merged the pull request. Thanks for the icon. I'm closing this issue now.
